### ISSUE TITLE
XrayKit not working in macos 

### ISSUE THREAD

**Issue by H-Khoujani** [arror/XrayKit#10]
I did a lot of tests but it didn't work in MacOS should I download last xray-core binary and run it with create new process and send argument to it ?

**Comment by hosseinkhojany** [comment]
ورژن اخر هست 1.79 
شما برای مک با چه روشی تونل میکنید کل سیستم را ؟

**Comment by arror** [comment]
0.1.79在我的 mac 上可以正常运行。
https://github.com/arror/Xray-for-macOS/releases/download/0.1.0/Xray-for-macOS.zip
