### ISSUE TITLE
Version 0.1.79 says iOS, no library for this platform was found

### ISSUE THREAD

**Issue by houmie** [arror/XrayKit#11]
It seems something is missing for iOS.  

> /Users/houmie/Library/Developer/Xcode/DerivedData/tegant-ewigkyiwmukfdibbvzefbzcdfqhi/SourcePackages/artifacts/xraykit/XrayKit/XrayKit.xcframework:1:1 While building for iOS, no library for this platform was found in '/Users/houmie/Library/Developer/Xcode/DerivedData/tegant-ewigkyiwmukfdibbvzefbzcdfqhi/SourcePackages/artifacts/xraykit/XrayKit/XrayKit.xcframework'.

Thanks

**Comment by houmie** [comment]
Sure, thank you for your help.

**Comment by houmie** [comment]
Thanks, I just emailed you.

Let's hope that Arror will come back to us about this issue.

**Comment by arror** [comment]
0.1.80 添加了 iOS 及 iOS 模拟器的支持。
由于目前只是实验性的，所以暂时不提供源代码，仅提供编译的二进制产物。
如果需要支持 maccatalyst，我也可以添加。

0.1.80 提前合并了对 tun 的支持。
