### ISSUE TITLE
Is there an example of implementation for Mac OS

### ISSUE THREAD

**Issue by hosseinkhojany** [arror/XrayKit#8]
Is there an example of implementation for Mac OS? The program I wrote for iOS does not work for Mac OS.
In macOS, VPN connection is established, but data is not transmitted.
Do I need to make special settings for macOS?

**Comment by arror** [comment]
暂时没有 macOS 的实现。

如果 macOS 没有正常工作，是 Tun2Socks 没有把数据发给 Xray 么？

请提供一下 log？

**Comment by hosseinkhojany** [comment]
首先，在您看来，这段代码适用于 Mac OS，因为它在 iOS 中完美运行

import NetworkExtension
import XrayKit
import Tun2SocksKit
import os

class PacketTunnelProvider: NEPacketTunnelProvider, XrayClientProtocol, XrayOSLoggerProtocol, XrayEnvironmentProtocol {
    func reset() throws {
        print("")
    }
    
    func set(_ name: String?, value: String?) throws {
        print("")
    }
    
    func onPrepare(_ env: XrayEnvironmentProtocol?) throws {
        try env?.set("XRAY_LOCATION_CONFIG", value: MGConstant.configDirectory)
        try env?.set("XRAY_LOCATION_ASSET", value: MGConstant.assetDirectory)
    }
    
    func onServerRunning() {
            print("onServerRunning")
    }
    
    func onTrafficUpdate(_ up: Int64, down: Int64) {
        print("Traffic update: up = \(up), down = \(down)")
    }
    
    func onGeneralMessage(_ severity: String?, message: String?) {
        let level = MGLogModel.Severity(rawValue: Int(severity ?? "0") ?? 0) ?? .none
            guard let message = message, !message.isEmpty else {
                return
            }
            switch level {
            case .debug:
                NSLog("DEBUG", message)
            case .info:
                NSLog("INFO", message)
            case .warning:
                NSLog("WARNING", message)
            case .error:
                NSLog("ERROR", message)
            case .none:
                break
            }
    }
    
    override func startTunnel(options: [String : NSObject]? = nil) async throws {
        Darwin.sleep(13)
        let data = MGPacketTunnelManager.createConfigurationModel(config: options!["config"] as! String);
    
        let settings = NEPacketTunnelNetworkSettings(tunnelRemoteAddress: "254.1.1.1")
        settings.mtu = 9000
        let netowrk = MGNetworkModel.current
        settings.ipv4Settings = {
            let settings = NEIPv4Settings(addresses: ["198.18.0.1"], subnetMasks: ["255.255.0.0"])
            settings.includedRoutes = [NEIPv4Route.default()]
            if netowrk.hideVPNIcon {
                settings.excludedRoutes = [NEIPv4Route(destinationAddress: "0.0.0.0", subnetMask: "255.0.0.0")]
            }
            return settings
        }()
        settings.ipv6Settings = {
            guard netowrk.ipv6Enabled else {
                return nil
            }
            let settings = NEIPv6Settings(addresses: ["fd6e:a81b:704f:1211::1"], networkPrefixLengths: [64])
            settings.includedRoutes = [NEIPv6Route.default()]
            if netowrk.hideVPNIcon {
                settings.excludedRoutes = [NEIPv6Route(destinationAddress: "::", networkPrefixLength: 128)]
            }
            return settings
        }()
        settings.dnsSettings = NEDNSSettings(servers: ["8.8.8.8", "114.114.114.114"])
        do {
            
            try await self.setTunnelNetworkSettings(settings)
            try self.startXray(inboundPort: 10808, data: data?.buildConfigurationData(inboundPort: 10808) ?? nil)
            
            try self.startSocks5Tunnel(serverPort: 10808)
            
        } catch {
            throw error
        }
    }
    
    private func startXray(inboundPort: Int, data: Data?) throws {
        let xrayInstance = XrayInstance()
        if(data != nil){
            do {
                let dataStr = String(data: data!, encoding: .utf8)!
                print(dataStr)
                
                guard FileManager.default.createFile(atPath: MGConstant.configDirectory+"/config.json", contents: data) else {
                    throw NSError.newError("Xray Failed to write configuration file")
                }
                try xrayInstance.run(self)
            } catch {
                throw NSError.newError("do build failed")
            }
        }else{
            throw NSError.newError("data is nil build failed")
        }
    }
    
    
    private func startSocks5Tunnel(serverPort port: Int) throws {
        let config = """
        tunnel:
          name: tun0
          mtu: 9000
        socks5:
          port: \(port)
          address: ::1
          udp: 'tcp'
        misc:
          task-stack-size: 20480
          connect-timeout: 5000
          read-write-timeout: 60000
          log-file: stderr
          log-level: error
          limit-nofile: 65535
        """
        guard FileManager.default.createFile(atPath: MGConstant.configDirectory+"/config.yml", contents: config.data(using: .utf8)!) else {
            throw NSError.newError("Tunnel Failed to write configuration file")
        }
        DispatchQueue.global(qos: .userInitiated).async {
            Socks5Tunnel.run(withConfig: MGConstant.configDirectory+"/config.yml")
        }
    }
    
    override func stopTunnel(with reason: NEProviderStopReason) async {
        let message: String
        switch reason {
        case .none:
            message = "No specific reason."
        case .userInitiated:
            message = "The user stopped the provider."
        case .providerFailed:
            message = "The provider failed."
        case .noNetworkAvailable:
            message = "There is no network connectivity."
        case .unrecoverableNetworkChange:
            message = "The device attached to a new network."
        case .providerDisabled:
            message = "The provider was disabled."
        case .authenticationCanceled:
            message = "The authentication process was cancelled."
        case .configurationFailed:
            message = "The provider could not be configured."
        case .idleTimeout:
            message = "The provider was idle for too long."
        case .configurationDisabled:
            message = "The associated configuration was disabled."
        case .configurationRemoved:
            message = "The associated configuration was deleted."
        case .superceded:
            message = "A high-priority configuration was started."
        case .userLogout:
            message = "The user logged out."
        case .userSwitch:
            message = "The active user changed."
        case .connectionFailed:
            message = "Failed to establish connection."
        case .sleep:
            message = "The device went to sleep and disconnectOnSleep is enabled in the configuration."
        case .appUpdate:
            message = "The NEProvider is being updated."
        @unknown default:
            return
        }
        
        NSLog("stopTunnel", message)
    }
    
    func onAccessLog(_ message: String?) {
        message.flatMap {
            NSLog("onDNSLog", $0)
        }
    }
    
    func onDNSLog(_ message: String?) {
        message.flatMap {
            NSLog("onDNSLog", $0)
        }
    }
    
}
老实说，我不知道在哪里可以看到日志，抱歉，我是 iOS 新手

**Comment by hosseinkhojany** [comment]
<img width="710" alt="Screenshot 1402-01-26 at 4 02 33 PM" src="https://user-images.githubusercontent.com/37432839/232223953-5bd662f7-ce40-4bee-8992-1bd8849917e5.png">
另外，如果我不激活这个选项，隧道将不会连接

**Comment by arror** [comment]
手机连接 mac，在 mac 控制台应用里面看，前提是你用 NSLOG 或者 OSLog 输出日志。

**Comment by hosseinkhojany** [comment]
我在控制台中没有看到任何日志，甚至一次都没有

<img width="471" alt="Screenshot 1402-01-26 at 4 39 31 PM" src="https://user-images.githubusercontent.com/37432839/232225819-b8880837-63d3-4179-8eba-54de49584453.png">


好吧，如果隧道没有连接，我不应该在 VPN 部分看到这个，对吧，所以隧道会连接🤷

**Comment by arror** [comment]
最终生成的配置文件里面 log 部分是怎么样的呢？

**Comment by hosseinkhojany** [comment]
{
    "outbounds": [
        {
            "protocol": "vmess",
            "sendThrough": "0.0.0.0",
            "settings": {
                "vnext": [
                    {
                        "address": "MYSERVER",
                        "port": 443,
                        "users": [
                            {
                                "alterId": 0,
                                "id": "MY_USER",
                                "security": "auto"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "tls",
                "tlsSettings": {
                    "allowInsecure": false,
                    "disableSessionResumption": true,
                    "disableSystemRoot": false,
                    "serverName": "SERVER"
                },
                "wsSettings": {
                    "headers": {
                        "Host": "SERVER"
                    },
                    "path": "/"
                }
            },
            "tag": "proxy"
        },
        {
            "protocol": "freedom",
            "tag": "direct"
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        }
    ],
    "routing": {
        "balancers": [
        ],
        "domainMatcher": "hybrid",
        "domainStrategy": "AsIs",
        "rules": [
        ]
    }
}

**Comment by arror** [comment]
怎么没有 inbounds 和 log 呢？

**Comment by hosseinkhojany** [comment]
不好意思，我发的连接错了，现在已经调试好了，是这样的

{
  "routing": {
    "rules": [],
    "domainMatcher": "hybrid",
    "domainStrategy": "AsIs",
    "balancers": []
  },
  "inbounds": [
    {
      "port": 10808,
      "tag": "socks-in",
      "sniffing": {
        "routeOnly": false,
        "enabled": true,
        "excludedDomains": [],
        "metadataOnly": false,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "settings": {
        "udp": true,
        "auth": "noauth"
      },
      "protocol": "socks",
      "listen": "[::1]"
    },
    {
      "settings": {
        "allowTransparent": true
      },
      "port": 10809,
      "listen": "[::1]",
      "protocol": "http",
      "sniffing": {
        "routeOnly": false,
        "enabled": true,
        "excludedDomains": [],
        "metadataOnly": false,
        "destOverride": [
          "http",
          "tls"
        ]
      },
      "tag": "http-in"
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "tag": "proxy",
      "sendThrough": "0.0.0.0",
      "settings": {
        "vnext": [
          {
            "address": "",
            "users": [
              {
                "id": "",
                "alterId": 0,
                "security": "auto"
              }
            ],
            "port": 443
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "tlsSettings": {
          "allowInsecure": false,
          "disableSystemRoot": false,
          "serverName": "",
          "disableSessionResumption": true
        },
        "security": "tls",
        "wsSettings": {
          "path": "/",
          "headers": {
            "Host": ""
          }
        }
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom"
    },
    {
      "protocol": "blackhole",
      "tag": "block"
    }
  ]
}
我正在发送这个

**Comment by arror** [comment]
不过我还是没看到 log 的配置。

那还有问题么？

**Comment by hosseinkhojany** [comment]
配置日志到底是什么意思？好吧，问题是这个配置在 iOS 上工作正常，但在 Mac 上不工作

**Comment by hosseinkhojany** [comment]
什么都没有出现，即使我添加了这个

**Comment by arror** [comment]
请明确一点，我所指的控制台不是 Xcode 的，是 mac 的一个应用，打开之后，连接手机，过滤条件是 Xray 所在的进程。

不知道我们的理解是否一致？

**Comment by hosseinkhojany** [comment]
error	08:50:12.974900+0330	XrayTunnel	Bootstrapping; external subsystem UIKit_PKSubsystem refused setup

error	08:50:13.036864+0330	XrayTunnel	open flag(s) 0x01000000 are reserved for VFS use and do not affect behaviour when passed to sqlite3_open_v2

error	08:50:13.038285+0330	XrayTunnel	cannot open file at line 46922 of [554764a6e7]

error	08:50:13.038337+0330	XrayTunnel	os_unix.c:46922: (2) open(/private/var/db/DetachedSignatures) - No such file or directory

default	08:50:13.070147+0330	XrayTunnel	Signature check failed: code failed to satisfy specified code requirement(s)

这些是我得到的错误

**Comment by arror** [comment]
> error 08:50:12.974900+0330 XrayTunnel Bootstrapping; external subsystem UIKit_PKSubsystem refused setup
> 
> error 08:50:13.036864+0330 XrayTunnel open flag(s) 0x01000000 are reserved for VFS use and do not affect behaviour when passed to sqlite3_open_v2
> 
> error 08:50:13.038285+0330 XrayTunnel cannot open file at line 46922 of [554764a6e7]
> 
> error 08:50:13.038337+0330 XrayTunnel os_unix.c:46922: (2) open(/private/var/db/DetachedSignatures) - No such file or directory
> 
> default 08:50:13.070147+0330 XrayTunnel Signature check failed: code failed to satisfy specified code requirement(s)
> 
> 这些是我得到的错误

这些都不是 xray 的日志，如果你不清楚哪些是 xray 的日志，请提供 xray 启动时该进程所有的日志信息包括简介信息和调试信息。
