### ISSUE TITLE
Availability of Static Library 

### ISSUE THREAD

**Issue by gurmeherchawla** [arror/XrayKit#9]
Is it possible to provide a static library option?

**Comment by arror** [comment]
> Is it possible to provide a static library option?

有什么不得不这样做的理由么？

**Comment by gurmeherchawla** [comment]
There are linking conflicts and duplicate symbols errors occurring with Dynamic Library

**Comment by gurmeherchawla** [comment]
Greetings @arror. Is there any update?

**Comment by gurmeherchawla** [comment]
@arror ?

**Comment by arror** [comment]
> @arror ?

可否 PR 编译脚本？
